language: php

php:
  - 7
  - 7.1
  - 7.2
  - nightly

dist: trusty

before_install:
  - composer selfupdate

install:
  - composer install --prefer-source --dev

script:
  - php vendor/bin/phpunit
  - vendor/bin/phpstan analyze -l 4 src tests examples
  - php vendor/bin/phpcs -n --standard=PSR1,PSR2 --report=full src/ tests/ examples/

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover build/docs/clover.xml; fi;'

matrix:
    fast_finish: true
